### ISSUE TITLE
Exception when I try to run the tests

### ISSUE THREAD

**Issue by theofilis** [KaramelaDAO/lolipop#1]
I get the following exception

```
An unexpected error occurred:

ReferenceError: web3 is not defined
    at Object.<anonymous> (C:\Users\theofilis\Project\contracts\lolipop\token-smart-contract\hardhat.config.js:29:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at importCsjOrEsModule (C:\Users\theofilis\Project\contracts\lolipop\node_modules\hardhat\src\internal\core\config\config-loading.ts:23:20)
    at loadConfigAndTasks (C:\Users\theofilis\Project\contracts\lolipop\node_modules\hardhat\src\internal\core\config\config-loading.ts:75:18)
    at main (C:\Users\theofilis\Project\contracts\lolipop\node_modules\hardhat\src\internal\cli\cli.ts:142:38)
```

**Comment by jonromero** [comment]
I forgot to add a dependancy for testing :D

Will add!
